// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJmVsA2RpX-Tkxt2ybQV3Vf6XdfC_t8fY',
    appId: '1:337993932386:web:1684aa05b2e4ac23e67b3b',
    messagingSenderId: '337993932386',
    projectId: 'portfolio-c3a00',
    authDomain: 'portfolio-c3a00.firebaseapp.com',
    storageBucket: 'portfolio-c3a00.firebasestorage.app',
    measurementId: 'G-0VFQ9ZVM11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAlHNc4P8jw36fUPgFFbO0XaOfFesoyZA',
    appId: '1:337993932386:android:b1b7be78faa9f0ace67b3b',
    messagingSenderId: '337993932386',
    projectId: 'portfolio-c3a00',
    storageBucket: 'portfolio-c3a00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDefrwcyDsRgaxCKmKTDOFobGiKDHwYYBk',
    appId: '1:337993932386:ios:b3ef4cbf248ff73fe67b3b',
    messagingSenderId: '337993932386',
    projectId: 'portfolio-c3a00',
    storageBucket: 'portfolio-c3a00.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
}
